# Generated by Django 3.2.5 on 2021-07-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poet',
            options={'ordering': ['name']},
        ),
    ]
