# Generated by Django 3.2.5 on 2021-07-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0003_era'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poetry.era'),
        ),
    ]
