# Generated by Django 3.2.5 on 2021-08-02 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0004_alter_poet_era'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poetry.poet')),
            ],
            options={
                'ordering': ['head'],
            },
        ),
    ]
