# Generated by Django 3.2.5 on 2021-08-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0005_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
