# Generated by Django 3.2.5 on 2021-08-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0006_alter_poem_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='head',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
